### ISSUE TITLE
Syntax issue in Type.py

### ISSUE THREAD

**Issue by KaviyaPeriyasamy** [kid1194/frappe_alerts#6]
### App Versions
```
{
	"active_users": "1.0.10",
	"alerts": "1.0.3",
	"builder": "1.8.0",
	"chat": "0.0.1",
	"erpnext": "15.18.3",
	"frappe": "15.19.1",
	"frappe_pdf": "0.0.1",
	"hrms": "15.15.0",
	"india_compliance": "15.7.0",
	"lms": "1.0.0",
	"payments": "0.0.1",
	"print_designer": "1.0.0",
	"sheets": "0.0.1",
	"tldraw_whiteboard": "0.0.1",
	"wiki": "2.0.0"
}
```
### Route
```
List/DocType/List
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 110, in application
    response = frappe.api.handle(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
           ^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1718, in call
    return fn(*args, **newargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/alerts/alerts/utils/alert.py", line 90, in user_alerts
    from .type import get_types
  File "apps/alerts/alerts/utils/type.py", line 11
    _type_dt_ = "Alert Type")
                            ^
SyntaxError: unmatched ')'

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"init": 1
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/alerts.utils.user_alerts",
	"request_id": "b0df388c-4be9-4124-b288-d099d0227a04"
}
```
### Response Data
```
{
	"exception": "SyntaxError: unmatched ')'",
	"exc_type": "SyntaxError",
	"_exc_source": "alerts (app)"
}
```

**Comment by KaviyaPeriyasamy** [comment]
@kid1194 Can you fix it on higher priority - Very minor bug?

**Comment by kid1194** [comment]
@KaviyaPeriyasamy Hey bro...

Sorry for the late reply, I was on holiday..

First, thank you for reporting this..
I have updated the plugin, so please give it another try and let me know if you face any problem..

Best regards..
