### ISSUE TITLE
Changing Display Timeout [BUG]: 

### ISSUE THREAD

**Issue by neomrx** [kid1194/frappe_alerts#8]
Dear @kid1194 ,

I received an error message when attempting to change the Display Timeout. Here’s the image associated with the log error:

![image](https://github.com/kid1194/frappe_alerts/assets/32833895/5c370a47-1c12-4be0-9333-5f91fd92cc23)

thanks in advance,
Log:

VM250:1 Console a été effacée.
undefined
request.js:279 
        

send @ jquery.js:9930
ajax @ jquery.js:9511
frappe.request.call @ request.js:279
frappe.call @ request.js:109
_call @ save.js:246
save @ save.js:23
frappe.ui.form.save @ save.js:273
(anonymes) @ form.js:820
Promise.then (asynchrone)
(anonymes) @ dom.js:262
frappe.run_serially @ dom.js:260
validate_and_save @ form.js:811
(anonymes) @ form.js:750
save @ form.js:747
Save @ toolbar.js:687
(anonymes) @ page.js:305
dispatch @ jquery.js:5135
elemData.handle @ jquery.js:4939
Afficher 4 plus de cadres
Afficher moins
request.js:473  Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 110, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1718, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/desk/form/save.py", line 39, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 335, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 388, in _save
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1126, in run_post_save_methods
    self.run_method("on_update")
  File "apps/frappe/frappe/model/document.py", line 960, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1320, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1302, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 957, in fn
    return method_object(*args, **kwargs)
  File "apps/alerts/alerts/alerts/doctype/alert_type/alert_type.py", line 59, in on_update
    self._emit_change()
  File "apps/alerts/alerts/alerts/doctype/alert_type/alert_type.py", line 96, in _emit_change
    "background": cstr(self.background),
NameError: name 'cstr' is not defined

(anonymes) @ request.js:473
frappe.request.cleanup @ request.js:471
(anonymes) @ request.js:325
fire @ jquery.js:3213
fireWith @ jquery.js:3343
done @ jquery.js:9619
(anonymes) @ jquery.js:9878
load (asynchrone)
send @ jquery.js:9897
ajax @ jquery.js:9511
frappe.request.call @ request.js:279
frappe.call @ request.js:109
_call @ save.js:246
save @ save.js:23
frappe.ui.form.save @ save.js:273
(anonymes) @ form.js:820
Promise.then (asynchrone)
(anonymes) @ dom.js:262
frappe.run_serially @ dom.js:260
validate_and_save @ form.js:811
(anonymes) @ form.js:750
save @ form.js:747
Save @ toolbar.js:687
(anonymes) @ page.js:305
dispatch @ jquery.js:5135
elemData.handle @ jquery.js:4939
Afficher 8 plus de cadres
Afficher moins

**Comment by kid1194** [comment]
@neomrx Thank you buddy for reporting this..

I have fixed the bug so I hope that everything works well..

Best regards..

**Comment by neomrx** [comment]
@kid1194 , thanks for your prompt response,
work verry well !!!
